services:
- mysql
language: php
php:
- 7.2.10
notifications:
  email: false
addons:
  sonarcloud:
    organization: ruijan-github
    projectKey: ExpensesWebsite
    token:
      secure: a13f01ed89e5d3975de0736eeeec33c0de9eb91b
deploy:
  provider: gae
  keyfile: expenses-238118-5f3c15437165.json
  project: expenses-238118
  verbosity: debug
  on: prod
install:
- composer require --dev phpunit/phpunit ^7.4
- curl -s http://getcomposer.org/installer | php
- php composer.phar install -n
script:
- php vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
- php vendor/bin/codacycoverage clover build/logs/clover.xml
before-install:
- openssl aes-256-cbc -K $encrypted_8d17a9479776_key -iv $encrypted_8d17a9479776_iv -in expenses-238118-7f87df2ef95c.json.enc -out expenses-238118-7f87df2ef95c.json -d