services:
- mysql

language: php

php:
- 7.2.10

notifications:
  email: false

install:
- composer require --dev phpunit/phpunit ^7.4
- curl -s http://getcomposer.org/installer | php
- php composer.phar install -n
- export CODACY_PROJECT_TOKEN=5960f38a16e74a9d891fbfed681d2251

script:
- php vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
- php vendor/bin/codacycoverage clover build/logs/clover.xml
